# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/news.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10proto/news.proto\x12\x08\x65ntities\"\xec\x01\n\x04News\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0e\n\x06\x41uthor\x18\x02 \x01(\t\x12\x11\n\tCreatedAt\x18\x03 \x01(\x03\x12\x11\n\tUpdatedAt\x18\x04 \x01(\x03\x12\x10\n\x08Headline\x18\x05 \x01(\t\x12\x0f\n\x07Summary\x18\x06 \x01(\t\x12\x0f\n\x07\x43ontent\x18\x07 \x01(\t\x12\x0b\n\x03URL\x18\x08 \x01(\t\x12\x0f\n\x07Symbols\x18\t \x03(\t\x12\x13\n\x0b\x46ingerprint\x18\n \x01(\t\x12\x0e\n\x06Source\x18\x0b \x01(\t\x12+\n\nSentiments\x18\x0c \x03(\x0b\x32\x17.entities.NewsSentiment\"\xe3\x01\n\rNewsSentiment\x12\x11\n\tTimestamp\x18\x01 \x01(\x03\x12\x1c\n\x04News\x18\x02 \x01(\x0b\x32\x0e.entities.News\x12\x11\n\tSentiment\x18\x03 \x01(\t\x12 \n\x18SentimentAnalysisProcess\x18\x04 \x01(\t\x12\x13\n\x0b\x46ingerprint\x18\x05 \x01(\t\x12\x0b\n\x03LLM\x18\x06 \x01(\t\x12\x0e\n\x06Symbol\x18\x07 \x01(\t\x12\x14\n\x0cSystemPrompt\x18\x08 \x01(\t\x12\x0e\n\x06\x46\x61iled\x18\t \x01(\x08\x12\x14\n\x0cRawSentiment\x18\n \x01(\tB\x0bZ\tentities/b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.news_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    _globals['DESCRIPTOR']._options = None
    _globals['DESCRIPTOR']._serialized_options = b'Z\tentities/'
    _globals['_NEWS']._serialized_start = 31
    _globals['_NEWS']._serialized_end = 267
    _globals['_NEWSSENTIMENT']._serialized_start = 270
    _globals['_NEWSSENTIMENT']._serialized_end = 497
# @@protoc_insertion_point(module_scope)
