# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/orderbook.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x15proto/orderbook.proto\x12\x08\x65ntities\"=\n\x0eOrderbookEntry\x12\r\n\x05Price\x18\x01 \x01(\x01\x12\x0c\n\x04Size\x18\x02 \x01(\x01\x12\x0e\n\x06Source\x18\x03 \x01(\t\"\xd8\x01\n\tOrderbook\x12\x0e\n\x06Symbol\x18\x01 \x01(\t\x12\x10\n\x08\x45xchange\x18\x02 \x01(\t\x12\x11\n\tTimestamp\x18\x03 \x01(\x03\x12&\n\x04\x41sks\x18\x04 \x03(\x0b\x32\x18.entities.OrderbookEntry\x12&\n\x04\x42ids\x18\x05 \x03(\x0b\x32\x18.entities.OrderbookEntry\x12\r\n\x05Reset\x18\x06 \x01(\x08\x12\x13\n\x0b\x46ingerprint\x18\x07 \x01(\t\x12\x0e\n\x06Source\x18\x08 \x01(\t\x12\x12\n\nAssetClass\x18\t \x01(\tB\x0bZ\tentities/b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.orderbook_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    _globals['DESCRIPTOR']._options = None
    _globals['DESCRIPTOR']._serialized_options = b'Z\tentities/'
    _globals['_ORDERBOOKENTRY']._serialized_start = 35
    _globals['_ORDERBOOKENTRY']._serialized_end = 96
    _globals['_ORDERBOOK']._serialized_start = 99
    _globals['_ORDERBOOK']._serialized_end = 315
# @@protoc_insertion_point(module_scope)
