# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/transmission_message.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n proto/transmission_message.proto\x12\x08\x65ntities\";\n\x07Message\x12\r\n\x05Topic\x18\x01 \x01(\t\x12\x0f\n\x07Payload\x18\x02 \x01(\x0c\x12\x10\n\x08\x44\x61taType\x18\x03 \x01(\tB\x0bZ\tentities/b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.transmission_message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    _globals['DESCRIPTOR']._options = None
    _globals['DESCRIPTOR']._serialized_options = b'Z\tentities/'
    _globals['_MESSAGE']._serialized_start = 46
    _globals['_MESSAGE']._serialized_end = 105
# @@protoc_insertion_point(module_scope)
